name: CI

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build_ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Packages
        run: sudo apt update

      - name: Install SFML
        run: sudo apt install -y libsfml-dev

      - name: Generate Build File
        run: cmake . -B build

      - name: Build Project
        run: cmake --build build