name: CI

on: [push]

defaults:
    run:
        shell: bash

jobs:
    build_and_test:
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]

        name: Build
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Install Required Dependencies on Ubuntu
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                sudo apt update
                sudo apt install -y libx11-dev xserver-xorg-dev xorg-dev libudev-dev libopenal-dev libvorbis-dev

            - name: Generate Build File
              run: cmake . -B build/ -DCMAKE_BUILD_TYPE=Debug

            - name: Build Project
              run: cmake --build build/
